spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASS:}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-properties:
        prepareThreshold: 0
      data-source-properties:
        prepareThreshold: 0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:true}

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8000}

allowed:
  origins: ${ALLOWED_ORIGINS:*}

webhook:
  base:
    url: ${WEBHOOK_BASE_URL:http://localhost:8080}

